try {
  throw Error('this is an error');
} catch (e) {
  console.log(e);
}